[project]
name = "flaskr"
version = "1.0.0"
description = "A basic todo list app built with Flask and RethinkDB."
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"